import {colors, diagram, fonts} from '../../styles/baseStyle';
import general from '../../styles/generalStyle';

const styles = {
  todo: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  dateText: {
    // fontSize: fonts.lg,
    display: 'none',
  },
  todoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: diagram.margin,
    paddingTop: diagram.margin,
    paddingBottom: diagram.padding,
    paddingLeft: diagram.margin, // * 2.5,
    borderRadius: 10,
    // justifyContent: 'space-between',
    // backgroundColor: colors.bgLight,
    // borderBottomWidth: 0.4,
    // borderColor: colors.dim,
  },
  headerTitle: {
    color: colors.white,
    fontSize: fonts.lg + 15,
    fontFamily: fonts.family.regular,
  },
  list: {
    paddingTop: diagram.padding,
    // marginTop: diagram.padding,
    // borderTopWidth: 0.3,
    // borderTopColor: colors.bgLight2,
  },
  listHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    // justifyContent: 'space-between',
    paddingBottom: diagram.padding,
    paddingLeft: diagram.margin, // * 2.67,
    paddingRight: diagram.margin + 1,
    // display: 'none',
    // borderBottomWidth: 0.5,
    // borderBottomColor: colors.bgLight2,
  },
  tasksNumbers: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: -2,
    marginLeft: 10,
    padding: 2,
    paddingLeft: 5,
    paddingRight: 5,
    borderWidth: 0.3,
    borderColor: colors.main,
    borderRadius: 100,
  },
  remaining: {
    color: colors.main,
    fontSize: fonts.sm - 4,
    letterSpacing: 1,
  },
  separador: {
    marginTop: diagram.padding,
    marginBottom: diagram.padding - 3,
    marginLeft: diagram.margin,
    width: 30,
    height: 0.4,
    backgroundColor: colors.dim,
    // alignSelf: 'center',
    borderRadius: 100,
    display: 'none',
  },
  rightSide: {
    marginLeft: 'auto',
    // marginRight: 3,
    width: 55, // 56,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    // alignSelf: 'flex-end',
    // backgroundColor: 'red',
  },
  addArea: {
    position: 'absolute',
    bottom: 20, // diagram.margin * 3.2,
    // right: 18, // diagram.margin - 4,
    alignSelf: 'center',
    zIndex: 2,
  },
  addModal: {
    marginTop: 'auto',
    padding: diagram.margin,
    paddingBottom: 6,
    paddingTop: 16,
    // height: 115,
    // justifyContent: 'space-around',
    backgroundColor: colors.bg,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  addButton: {
    justifyContent: 'center',
    alignItems: 'center',
    // alignSelf: 'flex-end',
    // marginTop: 11,
    // marginLeft: 17,
    // marginRight: 2,
    // marginBottom: 10, // -diagram.margin * 1.8,
    height: 72,
    width: 72,
    backgroundColor: colors.bgLight,
    borderColor: colors.bg,
    borderWidth: 6,
    borderRadius: 50,
    // elevation: 2,
  },
  menuButton: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    left: 18,
    bottom: 0, // -diagram.margin * 1.8,
    height: 48,
    width: 48,
    // backgroundColor: colors.main,
    borderRadius: 50,
    // elevation: 2,
  },
  footer: {
    height: 50,
    backgroundColor: colors.bgLight,
  },
  addHead: {
    borderBottomWidth: 0.4,
    borderBottomColor: colors.dim2,
    paddingBottom: diagram.padding,
    marginBottom: diagram.padding,
  },
  inputTask: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  taskTitle: {
    flex: 1,
    marginLeft: 10,
    color: colors.dim,
    fontSize: fonts.md,
    fontFamily: fonts.family.regular,
  },
  taskDescription: {
    marginLeft: diagram.margin + 8,
    color: colors.dim,
    fontSize: fonts.md - 1,
    fontFamily: fonts.family.regular,
    paddingBottom: 10,
  },
  newTaskDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    paddingLeft: 1,
  },
  taskItem: {
    flexDirection: 'row',
    marginRight: diagram.margin,
    justifyContent: 'space-around',
    alignItems: 'center',
    // paddingLeft: diagram.margin - 10,
    // paddingRight: diagram.margin - 10,
    // padding: 7,
    // borderWidth: 0.3,
    // borderColor: colors.dim,
    // borderRadius: 100,
  },
  taskSend: {
    marginLeft: 'auto',
  },
  ...general,
};

export default styles;
