import {colors, diagram, fonts} from '../../styles/baseStyle';
import general from '../../styles/generalStyle';

const styles = {
  todo: {
    // flex: 1,
    // paddingTop: 12,
    backgroundColor: colors.bg,
  },
  container: {
    // flex: 1,
    // paddingBottom: 50,
    // marginBottom: 500,
  },
  todoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingRight: diagram.padding - 5,
    paddingTop: diagram.padding - 6,
    paddingBottom: diagram.margin - 11,
    paddingLeft: diagram.margin - 6, // * 2.7,
    // backgroundColor: colors.bgLight,
    // borderBottomWidth: 0.4,
    // borderColor: colors.dim,
    borderRadius: 10,
    margin: 8,
  },
  headerTitle: {
    // marginLeft: diagram.margin, // diagram.margin - 4,
    // marginBottom: 5,
    marginTop: -6,
    color: colors.dim,
    fontSize: fonts.lg + 3,
    // textTransform: 'uppercase',
    fontWeight: 'bold',
    // alignSelf: 'center',
    // display: 'none',
  },
  tasksNumbers: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: -2,
    marginLeft: 10,
    // marginLeft: 'auto',
    // width: 62,
    // height: 26,
    padding: 2,
    paddingLeft: 7,
    paddingRight: 7,
    borderWidth: 0.3,
    borderColor: colors.dim,
    borderRadius: 100,
  },
  rightSide: {
    // marginLeft: 'auto',
    marginRight: 3,
    width: 95, // 56,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    // alignSelf: 'flex-end',
    // backgroundColor: 'red',
  },
  avatar: {
    // marginLeft: 'auto',
    width: 32,
    height: 32,
    borderRadius: 100,
    // display: 'none',
  },
  remaining: {
    // marginTop: 6,
    color: colors.dim,
    fontSize: fonts.sm - 2,
    textTransform: 'lowercase',
    letterSpacing: 1,
  },
  list: {
    // alignItems: 'center',
    // marginLeft: 6,
    // marginRight: 6,
  },
  listHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    // justifyContent: 'space-between',
    paddingBottom: diagram.margin - 4,
    paddingLeft: diagram.margin + 4,
    paddingRight: diagram.margin + 1,
    // display: 'none',
    // borderBottomWidth: 0.5,
    // borderBottomColor: colors.bgLight2,
  },
  listName: {
    color: colors.dim,
    fontSize: fonts.sm - 1,
    textTransform: 'uppercase',
    fontWeight: 'bold',
  },
  addModal: {
    marginTop: 'auto',
    paddingLeft: diagram.margin,
    paddingRight: diagram.margin + 1,
    height: 115,
    justifyContent: 'space-around',
    // alignItems: 'center',
    backgroundColor: colors.bg,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  addArea: {
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: diagram.margin * 2.8,
    right: diagram.padding - 6,
    alignSelf: 'center',
  },
  addButton2: {
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10, // -diagram.margin * 1.8,
    height: 48, // 44,
    width: 48, // 44,
    backgroundColor: colors.bgLight,
    // borderColor: colors.bg,
    // borderWidth: 8,
    borderRadius: 12,
    elevation: 3,
  },
  menuButton: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    right: diagram.padding - 6,
    bottom: 12, // -diagram.margin * 1.8,
    height: 48,
    width: 48,
    backgroundColor: colors.bgLight,
    borderRadius: 12,
    elevation: 3,
  },
  newTaskDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  inputTask: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  taskItem: {
    flexDirection: 'row',
    paddingLeft: diagram.margin - 10,
    paddingRight: diagram.margin - 10,
    padding: 7,
    marginRight: 8,
    justifyContent: 'space-around',
    alignItems: 'center',
    borderWidth: 0.3,
    borderColor: colors.dim,
    borderRadius: 100,
  },
  taskSend: {
    marginLeft: 'auto',
  },
  colors: {
    orange: colors.orange,
    white: colors.white,
    dim: colors.dim,
    green: colors.green,
    blue: colors.blue,
    red: colors.red,
    main: colors.main,
    bg: colors.bg,
  },
  ...general,
};

export default styles;
