import {colors, diagram, fonts} from '../../styles/baseStyle';
import general from '../../styles/generalStyle';

const styles = {
  todo: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  dateText: {
    marginTop: diagram.margin,
    marginBottom: diagram.margin,
    marginLeft: diagram.margin * 2.8,
    // alignSelf: 'center',
    color: colors.white,
    fontSize: fonts.lg + 5,
    // textTransform: 'capitalize',
    // fontWeight: 'bold',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
    paddingLeft: diagram.margin,
    height: 60,
    backgroundColor: colors.bg,
    borderTopWidth: 3,
    borderTopColor: colors.bg2,
  },
  dateHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    opacity: 0.5,
  },
  dayDate: {
    color: colors.white,
    fontSize: 30,
    marginRight: diagram.margin - 8,
  },
  headerTitle: {
    color: colors.white,
    marginLeft: 9,
    fontSize: 18,
  },
  remaining: {
    marginTop: -8,
    marginLeft: 4,
    color: colors.main,
    opacity: 0,
  },
  rightSide: {
    width: 160,
    marginLeft: 'auto',
    marginRight: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footerItem: {
    backgroundColor: colors.bg2,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
    height: 38,
    width: 38,
  },
  list: {
    // marginBottom: diagram.margin * 1.5,
  },
  listHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    // justifyContent: 'space-between',
    paddingBottom: diagram.margin - 4,
    paddingLeft: diagram.margin,
    paddingRight: diagram.margin + 1,
    display: 'none',
    // borderBottomWidth: 0.5,
    // borderBottomColor: colors.bgLight2,
  },
  addModal: {
    marginTop: 'auto',
    paddingLeft: diagram.margin,
    paddingRight: diagram.margin + 1,
    height: 115,
    justifyContent: 'space-around',
    backgroundColor: colors.bg,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  addArea: {
    // justifyContent: 'center',
    // alignItems: 'center',
    // position: 'absolute',
    // bottom: diagram.margin * 3,
    // right: diagram.margin + 1,
    // alignSelf: 'center',
  },
  addButton2: {
    justifyContent: 'center',
    alignItems: 'center',
    // alignSelf: 'center',
    // marginTop: 11,
    // marginLeft: 17,
    marginRight: 3,
    // marginBottom: diagram.margin,
    // height: 48,
    // width: 48,
    // backgroundColor: colors.main,
    // borderColor: colors.main,
    // borderWidth: 2,
    borderRadius: 50,
  },
  itemButton: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    // marginTop: 11,
    marginLeft: 17,
    marginRight: 17,
    marginBottom: diagram.margin,
    height: 44,
    width: 44,
    backgroundColor: colors.main,
    borderRadius: 100,
    // marginTop: -25,
    // height: 50,
    // width: 50,
  },
  inputTask: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  newTaskDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  taskItem: {
    flexDirection: 'row',
    // paddingLeft: diagram.margin - 10,
    // paddingRight: diagram.margin - 10,
    // padding: 5,
    marginRight: diagram.margin,
    // justifyContent: 'space-around',
    // alignItems: 'center',
    // borderWidth: 0.5,
    // borderColor: colors.opaco,
    // borderRadius: 100,
  },
  taskSend: {
    marginLeft: 'auto',
  },
  menuIcon: {
    // justifyContent: 'center',
    // alignItems: 'center',
    // width: 38,
    // height: 38,
    // paddingLeft: 2,
    // paddingRight: 0,
    // padding: 0,
    // borderWidth: 2,
    // borderColor: colors.icon,
    // borderRadius: 100,
  },
  colors: {
    orange: colors.orange,
    white: colors.white,
    dim: colors.dim,
    green: colors.green3,
    blue: colors.blue,
    red: colors.red,
    main: colors.main,
  },
  ...general,
};

export default styles;
