import { colors, diagram, fonts } from '../../styles/baseStyle';
import general from '../../styles/generalStyle';

const styles = {
   editArea: {
      width: '100%',
      // height: 180,
      backgroundColor: colors.bg,
      justifyContent: 'space-around',
      // padding: diagram.margin,
      // paddingRight: diagram.margin + 1,
      padding: diagram.margin,
      marginTop: 'auto',
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
   },
   top: {
      paddingBottom: diagram.margin,
      marginBottom: diagram.margin,
      borderBottomWidth: 0.3,
      borderBottomColor: colors.dim2,
      // backgroundColor: 'red',
   },
   titleComplete: {
      flexDirection: 'row',
      alignItems: 'center',
      // backgroundColor: 'blue',
   },
   taskTitle: {
      flex: 1,
      padding: 0,
      paddingLeft: 12,
      paddingRight: 12,
      color: colors.white,
      fontSize: fonts.md,
      fontFamily: fonts.family.regular,
      // backgroundColor: 'red',
   },
   taskDescription: {
      padding: 0,
      paddingLeft: diagram.margin * 1.87,
      color: colors.dim,
      fontSize: fonts.md - 1,
      fontFamily: fonts.family.regular,
      // backgroundColor: 'green',
   },
   mid: {
      marginTop: 'auto', // diagram.margin,
      // flexDirection: 'row',
      // alignItems: 'center',
      // marginBottom: diagram.margin,
      // borderBottomWidth: 0.3,
      // borderBottomColor: colors.bgLight2,
   },
   taskItem: {
      flexDirection: 'row',
      marginBottom: diagram.margin,
      paddingLeft: 4,
      // paddingRight: diagram.margin,
      // padding: 6,
      // marginRight: 10,
      // justifyContent: 'space-between',
      alignItems: 'center',
      // borderWidth: 0.5,
      // borderColor: colors.dim,
      // borderRadius: 100,
   },
   taskItem2: {
      flexDirection: 'row',
      // flex: 1,
      // paddingLeft: diagram.margin,
      // paddingRight: diagram.margin,
      // padding: 8,
      justifyContent: 'space-between',
      alignItems: 'center',
      // borderWidth: 0.3,
      // borderColor: colors.bgLight2,
      // borderRadius: 100,
   },
   bottom: {
      width: 80,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      alignSelf: 'flex-end',
   },
   tagModal: {
      justifyContent: 'space-evenly',
      width: '75%',
      height: 250,
      alignSelf: 'center',
      marginTop: 'auto',
      marginBottom: 'auto',
      backgroundColor: colors.bg,
      paddingLeft: diagram.margin * 2,
      paddingRight: diagram.margin + 1,
      borderRadius: 10,
   },
   tagItem: {
      flexDirection: 'row',
      alignItems: 'center',
   },
   colors: {
      orange: colors.orange,
      white: colors.white,
      dim: colors.dim,
      green: colors.green,
      blue: colors.blue,
      red: colors.red,
      main: colors.main,
   },
   ...general,
};

export default styles;
