import { colors, diagram, fonts } from '../../styles/baseStyle';
import general from '../../styles/generalStyle';

const styles = {
   dashboard: {
      backgroundColor: colors.bg,
      // paddingBottom: diagram.margin,
   },
   headerTitle: {
      padding: diagram.margin,
      // paddingLeft: diagram.margin * 2.6,
      // display: 'none',
      // alignSelf: 'center',
      // paddingTop: diagram.padding * 2,
      // paddingBottom: diagram.padding * 2,
   },
   dateView: {
      paddingLeft: diagram.margin,
      marginTop: 8,
      marginBottom: 8,
      // borderBottomWidth: 1,
      // borderBottomColor: colors.bgLight2,
      display: 'none',
   },
   todayDate: {
      color: colors.dim,
      fontSize: 16,
   },
   menuButton: {
      position: 'absolute',
      justifyContent: 'center',
      alignItems: 'center',
      right: diagram.margin,
      bottom: 16,
      height: 50,
      width: 50,
      backgroundColor: colors.bgLight2,
      borderRadius: 30,
      elevation: 2,
      // display: 'none',
   },

   // List --------------------------

   list: {
      // marginBottom: 16,
      // marginTop: diagram.padding,
      // paddingBottom: diagram.padding, // + 16,
      // borderBottomWidth: 1,
      // borderBottomColor: colors.bgLight2,
   },
   listHeader: {
      // paddingTop: 4,
      // paddingBottom: 8,
      // marginTop: 12,
      // marginBottom: 12,
      paddingLeft: diagram.margin,
      paddingRight: diagram.margin - 5,
      // backgroundColor: colors.bg2,
      // borderBottomWidth: 0.5,
      borderBottomColor: colors.bgLight2,
      alignItems: 'center',
      // display: 'none',
   },
   listName: {
      textTransform: 'capitalize',
      fontSize: fonts.md - 1,
      color: colors.mainAlt,
   },
   tasksNumbers: {
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 2, // -2,
      // marginLeft: 'auto', // 12, // 'auto',
      // padding: 2,
      // paddingLeft: 6,
      // paddingRight: 6,
      // borderWidth: 1,
      // borderColor: colors.main,
      // borderRadius: 100,
      // display: 'none',
      // backgroundColor: colors.main,
   },
   remaining: {
      marginTop: -1,
      marginLeft: 'auto', // 5,
      color: colors.dim,
      fontSize: fonts.md - 2, // fonts.sm - 1,
      fontFamily: fonts.family.bold,
      display: 'none',
      // letterSpacing: 1,
   },
   separator: {
      // alignSelf: 'center',
      width: 30,
      height: 0.4,
      backgroundColor: colors.dim,
      borderRadius: 100,
      marginTop: diagram.padding,
      marginBottom: diagram.padding / 2,
      display: 'none',
   },

   // Task ---------------------------

   todo: {
      alignItems: 'flex-start',
      // paddingTop: diagram.padding / 2,
      // paddingBottom: diagram.padding / 2,
      // justifyContent: 'flex-start',
      paddingLeft: diagram.margin,
      marginRight: diagram.margin,
      // paddingLeft: diagram.margin,
      // marginTop: 8,
      // marginBottom: 8,
      // borderBottomWidth: 0.5,
      // borderColor: colors.bgLight2,
      // borderRadius: 10,
      // elevation: 2,
      // backgroundColor: colors.bg2,
   },
   details: {
      // flex: 1,
      // width: '97%',
      marginLeft: 12,
      // marginRight: 20,
      marginTop: 5,
      flexDirection: 'row',
      alignItems: 'center',
      // backgroundColor: 'red',
      // display: 'none',
   },
   tag: {
      fontSize: fonts.sm - 1,
      // display: 'none',
   },
   time: {
      // width: 40,
      marginTop: -4,
      padding: 1,
      paddingBottom: 1,
      paddingLeft: 5,
      paddingRight: 5,
      borderWidth: 0.5,
      borderColor: colors.dim2,
      // backgroundColor: colors.green,
      borderRadius: 40,
      // diagram.padding / 2,
   },
   begin: {
      // fontFamily: fonts.family.bold,
      // color: colors.green2,
      fontSize: fonts.sm - 4,
   },
   left: {
      flex: 0,
      marginLeft: -2,
      // backgroundColor: 'red',
   },
   right: {
      marginLeft: diagram.padding,
      // alignItems: 'center',
      flex: 1,
      marginTop: 2,
      // marginBottom: 5,
      // padding: 6, // 7,
      // paddingLeft: 5, // // diagram.padding - 1,
      // paddingRight: diagram.padding - 1,
      // borderWidth: 0.3,
      // borderColor: colors.bgLight3,
      // backgroundColor: colors.bg2,
      // borderRadius: 100,
      // elevation: 1,
   },
   ...general,
};

export default styles;
