import { colors, diagram, fonts } from '../../styles/baseStyle';
import general from '../../styles/generalStyle';

const styles = {
   dashboard: {
      backgroundColor: colors.bg,
      // paddingBottom: diagram.margin,
   },
   headerTitle: {
      padding: diagram.margin,
      // paddingLeft: diagram.margin * 2.6,
      // display: 'none',
      // alignSelf: 'center',
      // paddingTop: diagram.padding * 2,
      // paddingBottom: diagram.padding * 2,
   },
   dateView: {
      paddingLeft: diagram.margin,
      marginTop: 8,
      marginBottom: 8,
      // borderBottomWidth: 1,
      // borderBottomColor: colors.bgLight2,
      display: 'none',
   },
   todayDate: {
      color: colors.dim,
      fontSize: 16,
   },
   menuButton: {
      position: 'absolute',
      justifyContent: 'center',
      alignItems: 'center',
      left: diagram.margin,
      bottom: 16,
      height: 50,
      width: 50,
      backgroundColor: colors.bgLight2,
      borderRadius: 30,
      elevation: 2,
      // display: 'none',
   },

   // List --------------------------

   list: {
      // marginBottom: 16,
      // marginTop: diagram.padding,
      // paddingBottom: diagram.padding, // + 16,
      // borderBottomWidth: 1,
      // borderBottomColor: colors.bgLight2,
   },
   listHeader: {
      paddingTop: 6,
      paddingBottom: 12,
      // marginTop: 12,
      marginBottom: 5,
      paddingLeft: diagram.margin,
      paddingRight: diagram.margin - 5,
      // backgroundColor: colors.bg2,
      borderBottomWidth: 0.7,
      borderBottomColor: colors.bgLight3,
      alignItems: 'center',
      // display: 'none',
   },
   listName: {
      // textTransform: 'uppercase',
      // marginLeft: diagram.padding + 1,
      fontSize: fonts.md,
      color: colors.white,
   },
   tasksNumbers: {
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 0, // -2,
      marginLeft: 'auto', // 12, // 'auto',
      // padding: 2,
      // paddingLeft: 6,
      // paddingRight: 6,
      // borderWidth: 1,
      // borderColor: colors.main,
      // borderRadius: 100,
      // display: 'none',
      // backgroundColor: colors.main,
   },
   remaining: {
      marginTop: -1,
      marginLeft: 'auto', // 5,
      color: colors.dim,
      fontSize: fonts.sm - 1,
      fontFamily: fonts.family.bold,
      // display: 'none',
      // letterSpacing: 1,
   },
   separator: {
      // alignSelf: 'center',
      width: 30,
      height: 0.4,
      backgroundColor: colors.dim,
      borderRadius: 100,
      marginTop: diagram.padding,
      marginBottom: diagram.padding / 2,
      display: 'none',
   },

   // Task ---------------------------

   todo: {
      // alignItems: 'center',
      paddingTop: 2, // diagram.padding,
      paddingBottom: 4, // diagram.padding / 2,
      // paddingLeft: 12,
      // paddingRight: 12,
      alignItems: 'flex-start',
      justifyContent: 'flex-start',
      marginLeft: diagram.margin,
      marginRight: diagram.margin,
      // paddingLeft: diagram.margin,
      // marginTop: 8,
      // marginBottom: 8,
      borderBottomWidth: 0.7,
      borderColor: colors.bgLight3,
      // borderRadius: 10,
      // elevation: 2,
      // backgroundColor: colors.bg2,
   },
   details: {
      // flex: 1,
      width: '97%',
      marginTop: 2,
      flexDirection: 'row',
      alignItems: 'center',
      // backgroundColor: 'red',
      // display: 'none',
   },
   tag: {
      fontSize: fonts.sm - 1,
   },
   time: {
      // width: 40,
      alignItems: 'center',
      marginTop: 2,
      // padding: 2,
      // paddingLeft: 9,
      // paddingRight: 9,
      // borderWidth: 0.3,
      // borderColor: colors.dim,
      // borderRadius: 15,
      // marginLeft: diagram.padding * 2,
   },
   begin: {
      // color: colors.white,
      marginTop: 1,
      fontSize: fonts.sm - 1,
   },
   right: {
      // alignItems: 'flex-start',
      // marginLeft: diagram.margin * 1.5,
      marginTop: 5,
      marginBottom: 5,
      padding: 6, // 7,
      paddingLeft: 5, // // diagram.padding - 1,
      paddingRight: diagram.padding - 1,
      // borderWidth: 0.3,
      borderColor: colors.bgLight3,
      // backgroundColor: colors.bg2,
      borderRadius: 100,
      // elevation: 1,
   },
   ...general,
};

export default styles;
