import {colors, diagram} from '../../styles/baseStyle';
import general from '../../styles/generalStyle';

const styles = {
  nav: {
    position: 'absolute',
    bottom: 20,
    right: 85,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    width: '70%',
    height: 52,
    paddingLeft: diagram.margin,
    paddingRight: diagram.margin + 1,
    backgroundColor: colors.bgLight,
    borderRadius: 100,
    // borderTopWidth: 1,
    // boderTopColor: colors.bg,
  },
  spotted: {
    // position: 'absolute',
    left: diagram.margin * 1.8,
    bottom: 10,
    width: 40,
    height: 70,
    backgroundColor: colors.main,
    borderRadius: 100,
    zIndex: 2,
    elevation: 1,
    display: 'none',
  },
  iconItem2: {
    // marginBottom: 8,
    // zIndex: 30,
    // elevation: 20,
    // backgroundColor: 'blue',
  },
  navItem: {
    // marginTop: -0,
    // paddingBottom: 8,
    justifyContent: 'center',
    alignItems: 'center',
    width: 60,
    height: 52,
    // backgroundColor: colors.bg,
    // borderBottomLeftRadius: 100,
    // borderBottomRightRadius: 100,
  },
  navItem2: {
    marginTop: -0,
    paddingBottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    width: 60,
    height: 52,
    backgroundColor: colors.bg,
    // borderBottomLeftRadius: 100,
    // borderBottomRightRadius: 100,
    // borderWidth: 1,
    // boderColor: colors.bg,
  },
  ...general,
};

export default styles;
