import { colors, diagram, fonts } from '../../styles/baseStyle';
import general from '../../styles/generalStyle';

const styles = {
   addArea: {
      position: 'absolute',
      bottom: 23,
      right: diagram.padding,
      // alignSelf: 'center',
      zIndex: 2,
   },
   addButton: {
      justifyContent: 'center',
      alignItems: 'center',
      // padding: 10,
      // paddingLeft: 30,
      // paddingRight: 30,
      backgroundColor: colors.main,
      // width: 140,
      width: 54,
      height: 54,
      borderRadius: 125,
      elevation: 2,
   },
   addModal: {
      marginTop: 'auto',
      // padding: diagram.margin,
      paddingBottom: 6,
      paddingTop: 8,
      // height: 115,
      // justifyContent: 'space-around',
      backgroundColor: colors.bg,
      // borderTopLeftRadius: 20,
      // borderTopRightRadius: 20,
   },
   addHead: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 0.5,
      borderColor: colors.dim2,
      marginLeft: diagram.padding / 2,
      marginRight: diagram.padding / 2,
      marginBottom: 8,
      paddingTop: diagram.padding / 2,
      paddingBottom: diagram.padding / 2,
      paddingLeft: diagram.margin,
      paddingRight: diagram.margin,
      borderRadius: 100,
      backgroundColor: colors.bg2,
   },
   inputTask: {
      flexDirection: 'row',
      alignItems: 'center',
   },
   taskTitle: {
      flex: 1,
      // marginLeft: diagram.padding,
      // height: 42,
      padding: 0,
      color: colors.dim,
      fontSize: fonts.md,
      // fontFamily: fonts.family.regular,
      // backgroundColor: 'red',
   },
   taskDescription: {
      padding: 0,
      color: colors.dim,
      fontSize: fonts.md - 2,
      // fontFamily: fonts.family.regular,
      // backgroundColor: 'blue',
      // paddingBottom: 10,
   },
   newTaskDetails: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderTopWidth: 0.4,
      borderTopColor: colors.dim2,
      // marginBottom: 10,
      paddingTop: diagram.padding,
      paddingBottom: diagram.padding - 6,
      paddingLeft: diagram.margin + 2,
      paddingRight: diagram.margin + 2,
      // elevation: 2,
   },
   taskItem: {
      flexDirection: 'row',
      marginRight: diagram.margin * 1.5,
      justifyContent: 'space-around',
      alignItems: 'center',
      // paddingLeft: diagram.margin - 10,
      // paddingRight: diagram.margin - 10,
      // padding: 7,
      // borderWidth: 0.3,
      // borderColor: colors.dim,
      // borderRadius: 100,
   },
   taskSend: {
      // marginLeft: 'auto',
      // marginRight: -2,
   },
   // List --------------------------

   // Task ---------------------------
   ...general,
};

export default styles;
